version: '3.8'
services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: better-melon
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: better-melon
    volumes:
      - postgres:/data/postgres/better-melon
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_APPENDONLY=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres:
  redis_data:
    driver: local