import { Type as t, type TObject } from "@sinclair/typebox";
import { animeDate } from "../anime/schema";

export const NullableFields = <T extends TObject<any>>(obj: T) =>
  t.Object(
    Object.fromEntries(
      Object.entries(obj.properties).map(([key, schema]) => [
        key,
        t.Union([schema as any, t.Null()])
      ])
    )
  )

export const anilistGenre = t.Union([
  t.Literal("Action"),
  t.Literal("Adventure"),
  t.Literal("Comedy"),
  t.Literal("Drama"),
  t.Literal("Ecchi"),
  t.Literal("Fantasy"),
  t.Literal("Hentai"),
  t.Literal("Horror"),
  t.Literal("Mahou Shoujo"),
  t.Literal("Mecha"),
  t.Literal("Music"),
  t.Literal("Mystery"),
  t.Literal("Psychological"),
  t.Literal("Romance"),
  t.Literal("Sci-Fi"),
  t.Literal("Slice of Life"),
  t.Literal("Sports"),
  t.Literal("Supernatural"),
  t.Literal("Thriller")
])

export const anilistStatus = t.Union([
  t.Literal("CANCELLED"),
  t.Literal("FINISHED"),
  t.Literal("HIATUS"),
  t.Literal("NOT_YET_RELEASED"),
  t.Literal("RELEASING")
])

export const anilistSeason = t.Union([
  t.Literal("SPRING"),
  t.Literal("FALL"),
  t.Literal("SUMMER"),
  t.Literal("WINTER")
])

export const anilistFormat = t.Union([
  t.Literal("TV"),
  t.Literal("TV_SHORT"),
  t.Literal("MOVIE"),
  t.Literal("SPECIAL"),
  t.Literal("OVA"),
  t.Literal("ONA"),
  t.Literal("MUSIC"),
  t.Literal("MANGA"),
  t.Literal("NOVEL"),
  t.Literal("ONE_SHOT"),
])

export const anilistSource = t.Union([
  t.Literal("ORIGINAL"),
  t.Literal("MANGA"),
  t.Literal("LIGHT_NOVEL"),
  t.Literal("VISUAL_NOVEL"),
  t.Literal("VIDEO_GAME"),
  t.Literal("NOVEL"),
  t.Literal("DOUJINSHI"),
  t.Literal("ANIME"),
  t.Literal("WEB_NOVEL"),
  t.Literal("LIVE_ACTION"),
  t.Literal("GAME"),
  t.Literal("COMIC"),
  t.Literal("MULTIMEDIA_PROJECT"),
  t.Literal("PICTURE_BOOK"),
  t.Literal("OTHER")
])

export const anilistSort = t.Union([
  t.Literal("ID"),
  t.Literal("ID_DESC"),
  t.Literal("TITLE_ROMAJI"),
  t.Literal("TITLE_ROMAJI_DESC"),
  t.Literal("TITLE_ENGLISH"),
  t.Literal("TITLE_ENGLISH_DESC"),
  t.Literal("TITLE_NATIVE"),
  t.Literal("TITLE_NATIVE_DESC"),
  t.Literal("TYPE"),
  t.Literal("TYPE_DESC"),
  t.Literal("FORMAT"),
  t.Literal("FORMAT_DESC"),
  t.Literal("START_DATE"),
  t.Literal("START_DATE_DESC"),
  t.Literal("END_DATE"),
  t.Literal("END_DATE_DESC"),
  t.Literal("SCORE"),
  t.Literal("SCORE_DESC"),
  t.Literal("POPULARITY"),
  t.Literal("POPULARITY_DESC"),
  t.Literal("TRENDING"),
  t.Literal("TRENDING_DESC"),
  t.Literal("EPISODES"),
  t.Literal("EPISODES_DESC"),
  t.Literal("DURATION"),
  t.Literal("DURATION_DESC"),
  t.Literal("STATUS"),
  t.Literal("STATUS_DESC"),
  t.Literal("CHAPTERS"),
  t.Literal("CHAPTERS_DESC"),
  t.Literal("VOLUMES"),
  t.Literal("VOLUMES_DESC"),
  t.Literal("UPDATED_AT"),
  t.Literal("UPDATED_AT_DESC"),
  t.Literal("SEARCH_MATCH"),
  t.Literal("FAVOURITES"),
  t.Literal("FAVOURITES_DESC")	
])

export const anilistTitle = t.Object({
  english: t.String(),
  romaji: t.Optional(t.String()),
  native: t.Optional(t.String()),
})

export const anilistNextAiringEpisode = t.Object({
  episode: t.Number(),
  airingAt: t.Number(),
  timeUntilAiring: t.Number()
})

export const anilistCoverImage = t.Object({
  medium: t.String(),
  large: t.String(),
  extraLarge: t.String()
})

export const anilistTag = t.Union([
  t.Literal('4-koma'),
  t.Literal('Achromatic'),
  t.Literal('Achronological Order'),
  t.Literal('Acrobatics'),
  t.Literal('Acting'),
  t.Literal('Adoption'),
  t.Literal('Advertisement'),
  t.Literal('Afterlife'),
  t.Literal('Age Gap'),
  t.Literal('Age Regression'),
  t.Literal('Agender'),
  t.Literal('Agriculture'),
  t.Literal('Airsoft'),
  t.Literal('Alchemy'),
  t.Literal('Aliens'),
  t.Literal('Alternate Universe'),
  t.Literal('American Football'),
  t.Literal('Amnesia'),
  t.Literal('Anachronism'),
  t.Literal('Ancient China'),
  t.Literal('Angels'),
  t.Literal('Animals'),
  t.Literal('Anthology'),
  t.Literal('Anthropomorphism'),
  t.Literal('Anti-Hero'),
  t.Literal('Archery'),
  t.Literal('Aromantic'),
  t.Literal('Arranged Marriage'),
  t.Literal('Artificial Intelligence'),
  t.Literal('Asexual'),
  t.Literal('Assassins'),
  t.Literal('Astronomy'),
  t.Literal('Athletics'),
  t.Literal('Augmented Reality'),
  t.Literal('Autobiographical'),
  t.Literal('Aviation'),
  t.Literal('Badminton'),
  t.Literal('Band'),
  t.Literal('Bar'),
  t.Literal('Baseball'),
  t.Literal('Basketball'),
  t.Literal('Battle Royale'),
  t.Literal('Biographical'),
  t.Literal('Bisexual'),
  t.Literal('Blackmail'),
  t.Literal('Board Game'),
  t.Literal('Boarding School'),
  t.Literal('Body Horror'),
  t.Literal('Body Image'),
  t.Literal('Body Swapping'),
  t.Literal('Bowling'),
  t.Literal('Boxing'),
  t.Literal('Boys Love'),
  t.Literal('Bullying'),
  t.Literal('Butler'),
  t.Literal('Calligraphy'),
  t.Literal('Camping'),
  t.Literal('Cannibalism'),
  t.Literal('Card Battle'),
  t.Literal('Cars'),
  t.Literal('Centaur'),
  t.Literal('CGI'),
  t.Literal('Cheerleading'),
  t.Literal('Chibi'),
  t.Literal('Chimera'),
  t.Literal('Chuunibyou'),
  t.Literal('Circus'),
  t.Literal('Class Struggle'),
  t.Literal('Classic Literature'),
  t.Literal('Classical Music'),
  t.Literal('Clone'),
  t.Literal('Coastal'),
  t.Literal('Cohabitation'),
  t.Literal('College'),
  t.Literal('Coming of Age'),
  t.Literal('Conspiracy'),
  t.Literal('Cosmic Horror'),
  t.Literal('Cosplay'),
  t.Literal('Cowboys'),
  t.Literal('Creature Taming'),
  t.Literal('Crime'),
  t.Literal('Criminal Organization'),
  t.Literal('Crossdressing'),
  t.Literal('Crossover'),
  t.Literal('Cult'),
  t.Literal('Cultivation'),
  t.Literal('Curses'),
  t.Literal('Cute Boys Doing Cute Things'),
  t.Literal('Cute Girls Doing Cute Things'),
  t.Literal('Cyberpunk'),
  t.Literal('Cyborg'),
  t.Literal('Cycling'),
  t.Literal('Dancing'),
  t.Literal('Death Game'),
  t.Literal('Delinquents'),
  t.Literal('Demons'),
  t.Literal('Denpa'),
  t.Literal('Desert'),
  t.Literal('Detective'),
  t.Literal('Dinosaurs'),
  t.Literal('Disability'),
  t.Literal('Dissociative Identities'),
  t.Literal('Dragons'),
  t.Literal('Drawing'),
  t.Literal('Drugs'),
  t.Literal('Dullahan'),
  t.Literal('Dungeon'),
  t.Literal('Dystopian'),
  t.Literal('E-Sports'),
  t.Literal('Eco-Horror'),
  t.Literal('Economics'),
  t.Literal('Educational'),
  t.Literal('Elderly Protagonist'),
  t.Literal('Elf'),
  t.Literal('Ensemble Cast'),
  t.Literal('Environmental'),
  t.Literal('Episodic'),
  t.Literal('Ero Guro'),
  t.Literal('Espionage'),
  t.Literal('Estranged Family'),
  t.Literal('Exorcism'),
  t.Literal('Fairy'),
  t.Literal('Fairy Tale'),
  t.Literal('Fake Relationship'),
  t.Literal('Family Life'),
  t.Literal('Fashion'),
  t.Literal('Female Harem'),
  t.Literal('Female Protagonist'),
  t.Literal('Femboy'),
  t.Literal('Fencing'),
  t.Literal('Filmmaking'),
  t.Literal('Firefighters'),
  t.Literal('Fishing'),
  t.Literal('Fitness'),
  t.Literal('Flash'),
  t.Literal('Food'),
  t.Literal('Football'),
  t.Literal('Foreign'),
  t.Literal('Found Family'),
  t.Literal('Fugitive'),
  t.Literal('Full CGI'),
  t.Literal('Full Color'),
  t.Literal('Gambling'),
  t.Literal('Gangs'),
  t.Literal('Gender Bending'),
  t.Literal('Ghost'),
  t.Literal('Go'),
  t.Literal('Goblin'),
  t.Literal('Gods'),
  t.Literal('Golf'),
  t.Literal('Gore'),
  t.Literal('Guns'),
  t.Literal('Gyaru'),
  t.Literal('Handball'),
  t.Literal('Henshin'),
  t.Literal('Heterosexual'),
  t.Literal('Hikikomori'),
  t.Literal('Hip-hop Music'),
  t.Literal('Historical'),
  t.Literal('Homeless'),
  t.Literal('Horticulture'),
  t.Literal('Ice Skating'),
  t.Literal('Idol'),
  t.Literal('Indigenous Cultures'),
  t.Literal('Inn'),
  t.Literal('Isekai'),
  t.Literal('Iyashikei'),
  t.Literal('Jazz Music'),
  t.Literal('Josei'),
  t.Literal('Judo'),
  t.Literal('Kaiju'),
  t.Literal('Karuta'),
  t.Literal('Kemonomimi'),
  t.Literal('Kids'),
  t.Literal('Kingdom Management'),
  t.Literal('Konbini'),
  t.Literal('Kuudere'),
  t.Literal('Lacrosse'),
  t.Literal('Language Barrier'),
  t.Literal('Long Strip'),
  t.Literal('Lost Civilization'),
  t.Literal('Love Triangle'),
  t.Literal('Mafia'),
  t.Literal('Magic'),
  t.Literal('Mahjong'),
  t.Literal('Maids'),
  t.Literal('Makeup'),
  t.Literal('Male Harem'),
  t.Literal('Male Protagonist'),
  t.Literal('Marriage'),
  t.Literal('Martial Arts'),
  t.Literal('Matchmaking'),
  t.Literal('Matriarchy'),
  t.Literal('Medicine'),
  t.Literal('Medieval'),
  t.Literal('Memory Manipulation'),
  t.Literal('Mermaid'),
  t.Literal('Meta'),
  t.Literal('Metal Music'),
  t.Literal('Military'),
  t.Literal('Mixed Gender Harem'),
  t.Literal('Mixed Media'),
  t.Literal('Monster Boy'),
  t.Literal('Monster Girl'),
  t.Literal('Mopeds'),
  t.Literal('Motorcycles'),
  t.Literal('Mountaineering'),
  t.Literal('Musical Theater'),
  t.Literal('Mythology'),
  t.Literal('Natural Disaster'),
  t.Literal('Necromancy'),
  t.Literal('Nekomimi'),
  t.Literal('Ninja'),
  t.Literal('No Dialogue'),
  t.Literal('Noir'),
  t.Literal('Non-fiction'),
  t.Literal('Nudity'),
  t.Literal('Nun'),
  t.Literal('Office'),
  t.Literal('Office Lady'),
  t.Literal('Oiran'),
  t.Literal('Ojou-sama'),
  t.Literal('Orphan'),
  t.Literal('Otaku Culture'),
  t.Literal('Outdoor Activities'),
  t.Literal('Pandemic'),
  t.Literal('Parenthood'),
  t.Literal('Parkour'),
  t.Literal('Parody'),
  t.Literal('Philosophy'),
  t.Literal('Photography'),
  t.Literal('Pirates'),
  t.Literal('Poker'),
  t.Literal('Police'),
  t.Literal('Politics'),
  t.Literal('Polyamorous'),
  t.Literal('Post-Apocalyptic'),
  t.Literal('POV'),
  t.Literal('Pregnancy'),
  t.Literal('Primarily Adult Cast'),
  t.Literal('Primarily Animal Cast'),
  t.Literal('Primarily Child Cast'),
  t.Literal('Primarily Female Cast'),
  t.Literal('Primarily Male Cast'),
  t.Literal('Primarily Teen Cast'),
  t.Literal('Prison'),
  t.Literal('Proxy Battle'),
  t.Literal('Psychosexual'),
  t.Literal('Puppetry'),
  t.Literal('Rakugo'),
  t.Literal('Real Robot'),
  t.Literal('Rehabilitation'),
  t.Literal('Reincarnation'),
  t.Literal('Religion'),
  t.Literal('Rescue'),
  t.Literal('Restaurant'),
  t.Literal('Revenge'),
  t.Literal('Robots'),
  t.Literal('Rock Music'),
  t.Literal('Rotoscoping'),
  t.Literal('Royal Affairs'),
  t.Literal('Rugby'),
  t.Literal('Rural'),
  t.Literal('Samurai'),
  t.Literal('Satire'),
  t.Literal('School'),
  t.Literal('School Club'),
  t.Literal('Scuba Diving'),
  t.Literal('Seinen'),
  t.Literal('Shapeshifting'),
  t.Literal('Ships'),
  t.Literal('Shogi'),
  t.Literal('Shoujo'),
  t.Literal('Shounen'),
  t.Literal('Shrine Maiden'),
  t.Literal('Skateboarding'),
  t.Literal('Skeleton'),
  t.Literal('Slapstick'),
  t.Literal('Slavery'),
  t.Literal('Snowscape'),
  t.Literal('Software Development'),
  t.Literal('Space'),
  t.Literal('Space Opera'),
  t.Literal('Spearplay'),
  t.Literal('Steampunk'),
  t.Literal('Stop Motion'),
  t.Literal('Succubus'),
  t.Literal('Suicide'),
  t.Literal('Sumo'),
  t.Literal('Super Power'),
  t.Literal('Super Robot'),
  t.Literal('Superhero'),
  t.Literal('Surfing'),
  t.Literal('Surreal Comedy'),
  t.Literal('Survival'),
  t.Literal('Swimming'),
  t.Literal('Swordplay'),
  t.Literal('Table Tennis'),
  t.Literal('Tanks'),
  t.Literal('Tanned Skin'),
  t.Literal('Teacher'),
  t.Literal('Teens Love'),
  t.Literal('Tennis'),
  t.Literal('Terrorism'),
  t.Literal('Time Loop'),
  t.Literal('Time Manipulation'),
  t.Literal('Time Skip'),
  t.Literal('Tokusatsu'),
  t.Literal('Tomboy'),
  t.Literal('Torture'),
  t.Literal('Tragedy'),
  t.Literal('Trains'),
  t.Literal('Transgender'),
  t.Literal('Travel'),
  t.Literal('Triads'),
  t.Literal('Tsundere'),
  t.Literal('Twins'),
  t.Literal('Unrequited Love'),
  t.Literal('Urban'),
  t.Literal('Urban Fantasy'),
  t.Literal('Vampire'),
  t.Literal('Vertical Video'),
  t.Literal('Veterinarian'),
  t.Literal('Video Games'),
  t.Literal('Vikings'),
  t.Literal('Villainess'),
  t.Literal('Virtual World'),
  t.Literal('Vocal Synth'),
  t.Literal('Volleyball'),
  t.Literal('VTuber'),
  t.Literal('War'),
  t.Literal('Werewolf'),
  t.Literal('Wilderness'),
  t.Literal('Witch'),
  t.Literal('Work'),
  t.Literal('Wrestling'),
  t.Literal('Writing'),
  t.Literal('Wuxia'),
  t.Literal('Yakuza'),
  t.Literal('Yandere'),
  t.Literal('Youkai'),
  t.Literal('Yuri'),
  t.Literal('Zombie')
])

export const anilistAnime = t.Object({
  id: t.Number(),
  title: anilistTitle,
  format: anilistFormat,
  status: anilistStatus,
  bannerImage: t.Union([
    t.String(),
    t.Null()
  ]),
  coverImage: anilistCoverImage,
  episodes: t.Union([
    t.Number(),
    t.Null()
  ]),
  nextAiringEpisode: t.Union([
    anilistNextAiringEpisode,
    t.Null()
  ]),
  startDate: animeDate,
  endDate: NullableFields(animeDate),
})