import { AnilistCountry, AnilistRelationType } from "@/types/anilist/anime"
import { Anime, AnimeQueryVariables, AnimeListQueryVariables } from "@/types/anime";
import { SearchFilters } from "@/types/search";
import { AnilistFormat, AnilistGenre, AnilistSeason, AnilistSort, AnilistSource, AnilistStatus, AnilistTag } from "@better-melon/shared/types"

export const queryVariables = {
  anime: {
    basic: ({ id }: { id: Anime['id'] }): AnimeQueryVariables => ({ 
      id,
      withTitle: true,
      withCoverImage: true,
      withStatus: true,
    }),
  
    dynamic: ({ id }: { id: Anime['id'] }): AnimeQueryVariables => ({
      id,
      withStatus: true,
      withEpisodes: true,
      withNextAiringEpisode: true
    }),
  
    infoHero: ({ id }: { id: Anime['id'] }): AnimeQueryVariables => ({
      id,
      withTitle: true,
      withBannerImage: true,
      withCoverImage: true,
      withAverageScore: true,
      withStatus: true,
      withSeasonYear: true,
      withFormat: true,
      withEpisodes: true,
      withGenres: true,
      withDuration: true,
    }),
  
    details: ({ id }: { id: Anime['id'] }): AnimeQueryVariables => ({
      id,
      withTitle: true,
      withStatus: true,
      withCoverImage: true,
      withSeason: true,
      withSeasonYear: true,
      withAverageScore: true,
      withEpisodes: true,
      withFormat: true,
      withDuration: true,
      withNextAiringEpisode: true,
      withBannerImage: true,
      withGenres: true,
      withDescription: true,
      withStudios: true,
      withStartDate: true,
      withEndDate: true,
      withCharacters: true,
      withRelations: true,
      withRecommendations: true,
      withTrailer: true,
    }),
  
    info: ({ id }: { id: Anime['id'] }): AnimeQueryVariables => ({
      ...queryVariables.anime.infoHero({ id }),
      ...queryVariables.anime.details({ id }),
    }),
  },
  list: {
    search: ({ 
      query, 
      page, 
      sorts, 
      genres, 
      tags, 
      status, 
      seasonYear, 
      format, 
      season, 
      isAdult, 
      source, 
      countryOfOrigin, 
      averageScore 
    }: SearchFilters): AnimeListQueryVariables => ({
      // Search & pagination
      query: query || undefined,
      page: Number(page) || 1,
      perPage: 15,
      
      // Filters - only include if they have actual values
      ...(sorts && { sorts }),
      ...(genres && { genres }),
      ...(tags && { tags }),
      ...(status && { status }),
      ...(seasonYear && { seasonYear: Number(seasonYear) }),
      ...(format && { format }),
      ...(season && { season }),
      ...(typeof isAdult === 'boolean' && { isAdult }),
      ...(source && { source }),
      ...(countryOfOrigin && { countryOfOrigin }),
      ...(averageScore && { averageScore: Number(averageScore) }),
      
      // Metadata - always included
      withTitle: true,
      withCoverImage: true,
      withStatus: true,
      withAverageScore: true,
      withSeasonYear: true,
      withFormat: true,
    }),
    quickSearch: ({ query, page = 1, perPage = 10 }: { query: string, page?: number, perPage?: number }): AnimeListQueryVariables => ({ 
      query,
      withTitle: true,
      withCoverImage: true,
      withStatus: true,
    }),
    topTrending: ({ page = 1, perPage = 10 }: { page?: number, perPage?: number }): AnimeListQueryVariables => ({ 
      sorts: ['TRENDING_DESC'],
      withTitle: true,
      withStatus: true,
      withCoverImage: true,
      withBannerImage: true,
      withSeasonYear: true,
      withDescription: true,
      withFormat: true,
      withAverageScore: true
    }),
    trending: ({ page = 1, perPage = 10 }: { page?: number, perPage?: number }): AnimeListQueryVariables => ({ 
      sorts: ['TRENDING_DESC'],
      withTitle: true,
      withFormat: true,
      withStatus: true,
      withCoverImage: true,
      withSeasonYear: true,
      withAverageScore: true
    }),
    popular: ({ page = 1, perPage = 10 }: { page?: number, perPage?: number }): AnimeListQueryVariables => ({ 
      sorts: ['POPULARITY_DESC'],
      withTitle: true,
      withFormat: true,
      withStatus: true,
      withCoverImage: true,
      withSeasonYear: true,
      withAverageScore: true
    }),
    favourite: ({ page = 1, perPage = 10 }: { page?: number, perPage?: number }): AnimeListQueryVariables => ({ 
      sorts: ['FAVOURITES_DESC'],
      withTitle: true,
      withFormat: true,
      withStatus: true,
      withCoverImage: true,
      withSeasonYear: true,
      withAverageScore: true
    }),
    topAiring: ({ page = 1, perPage = 10 }: { page?: number, perPage?: number }): AnimeListQueryVariables => ({ 
      sorts: ['TRENDING_DESC'],
      status: 'RELEASING',
      withFormat: true,
      withTitle: true,
      withStatus: true,
      withCoverImage: true,
      withSeasonYear: true,
      withAverageScore: true
    }),
    topUpcoming: ({ page = 1, perPage = 10 }: { page?: number, perPage?: number }): AnimeListQueryVariables => ({ 
      sorts: ['POPULARITY_DESC'],
      status: 'NOT_YET_RELEASED',
      withFormat: true,
      withTitle: true,
      withStatus: true,
      withCoverImage: true,
      withSeasonYear: true,
      withAverageScore: true
    }),
  }
};

export const animeGenres: AnilistGenre[] = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Ecchi",
    "Fantasy",
    "Hentai",
    "Horror",
    "Mahou Shoujo",
    "Mecha",
    "Music",
    "Mystery",
    "Psychological",
    "Romance",
    "Sci-Fi",
    "Slice of Life",
    "Sports",
    "Supernatural",
    "Thriller",
]

export const animeStatuses: AnilistStatus[] = [
    "CANCELLED",
    "FINISHED",
    "HIATUS",
    "NOT_YET_RELEASED",
    "RELEASING"
]

export const animeFormats: AnilistFormat[] = [
    "TV",
    "TV_SHORT",
    "MOVIE",
    "SPECIAL",
    "OVA",
    "ONA",
    "MUSIC",
    "MANGA",
    "NOVEL",
    "ONE_SHOT",
]

export const animeSeasons: AnilistSeason[] = [
    "FALL",
    "SPRING",
    "SUMMER",
    "WINTER"
]

export const animeSources: AnilistSource[] = [
    "ORIGINAL",
    "MANGA",
    "LIGHT_NOVEL",
    "VISUAL_NOVEL",
    "VIDEO_GAME",
    "OTHER",
    "NOVEL",
    "DOUJINSHI",
    "ANIME",
    "WEB_NOVEL",
    "LIVE_ACTION",
    "GAME",
    "COMIC",
    "MULTIMEDIA_PROJECT",
    "PICTURE_BOOK",
]

export const animeSorts: AnilistSort[] = [
    "ID",	
    "ID_DESC",	
    "TITLE_ROMAJI",	
    "TITLE_ROMAJI_DESC",	
    "TITLE_ENGLISH",	
    "TITLE_ENGLISH_DESC",	
    "TITLE_NATIVE",	
    "TITLE_NATIVE_DESC",	
    "TYPE",	
    "TYPE_DESC",	
    "FORMAT",	
    "FORMAT_DESC",	
    "START_DATE",	
    "START_DATE_DESC",	
    "END_DATE",	
    "END_DATE_DESC",	
    "SCORE",	
    "SCORE_DESC",	
    "POPULARITY",	
    "POPULARITY_DESC",	
    "TRENDING",	
    "TRENDING_DESC",	
    "EPISODES",	
    "EPISODES_DESC",	
    "DURATION",	
    "DURATION_DESC",	
    "STATUS",	
    "STATUS_DESC",	
    "CHAPTERS",	
    "CHAPTERS_DESC",	
    "VOLUMES",	
    "VOLUMES_DESC",	
    "UPDATED_AT",	
    "UPDATED_AT_DESC",	
    "SEARCH_MATCH",	
    "FAVOURITES",	
    "FAVOURITES_DESC"	
]

export const animeCountries: {
    value: AnilistCountry,
    label: string
}[] = [
    {
        value: "JP",
        label: "Japan"
    },
    {
        value: "KR",
        label: "South Korea"
    },
    {
        value: "TW",
        label: "Taiwan"
    },
    {
        value: "CN",
        label: "China"
    }
];

export const excludeRelations: AnilistRelationType[] = ['ADAPTATION', 'CHARACTER', 'SOURCE', "ALTERNATIVE"]

export const animeTags: AnilistTag[] = [
  "4-koma",
  "Achromatic",
  "Achronological Order",
  "Acrobatics",
  "Acting",
  "Adoption",
  "Advertisement",
  "Afterlife",
  "Age Gap",
  "Age Regression",
  "Agender",
  "Agriculture",
  "Airsoft",
  "Alchemy",
  "Aliens",
  "Alternate Universe",
  "American Football",
  "Amnesia",
  "Anachronism",
  "Ancient China",
  "Angels",
  "Animals",
  "Anthology",
  "Anthropomorphism",
  "Anti-Hero",
  "Archery",
  "Aromantic",
  "Arranged Marriage",
  "Artificial Intelligence",
  "Asexual",
  "Assassins",
  "Astronomy",
  "Athletics",
  "Augmented Reality",
  "Autobiographical",
  "Aviation",
  "Badminton",
  "Band",
  "Bar",
  "Baseball",
  "Basketball",
  "Battle Royale",
  "Biographical",
  "Bisexual",
  "Blackmail",
  "Board Game",
  "Boarding School",
  "Body Horror",
  "Body Image",
  "Body Swapping",
  "Bowling",
  "Boxing",
  "Boys Love",
  "Bullying",
  "Butler",
  "Calligraphy",
  "Camping",
  "Cannibalism",
  "Card Battle",
  "Cars",
  "Centaur",
  "CGI",
  "Cheerleading",
  "Chibi",
  "Chimera",
  "Chuunibyou",
  "Circus",
  "Class Struggle",
  "Classic Literature",
  "Classical Music",
  "Clone",
  "Coastal",
  "Cohabitation",
  "College",
  "Coming of Age",
  "Conspiracy",
  "Cosmic Horror",
  "Cosplay",
  "Cowboys",
  "Creature Taming",
  "Crime",
  "Criminal Organization",
  "Crossdressing",
  "Crossover",
  "Cult",
  "Cultivation",
  "Curses",
  "Cute Boys Doing Cute Things",
  "Cute Girls Doing Cute Things",
  "Cyberpunk",
  "Cyborg",
  "Cycling",
  "Dancing",
  "Death Game",
  "Delinquents",
  "Demons",
  "Denpa",
  "Desert",
  "Detective",
  "Dinosaurs",
  "Disability",
  "Dissociative Identities",
  "Dragons",
  "Drawing",
  "Drugs",
  "Dullahan",
  "Dungeon",
  "Dystopian",
  "E-Sports",
  "Eco-Horror",
  "Economics",
  "Educational",
  "Elderly Protagonist",
  "Elf",
  "Ensemble Cast",
  "Environmental",
  "Episodic",
  "Ero Guro",
  "Espionage",
  "Estranged Family",
  "Exorcism",
  "Fairy",
  "Fairy Tale",
  "Fake Relationship",
  "Family Life",
  "Fashion",
  "Female Harem",
  "Female Protagonist",
  "Femboy",
  "Fencing",
  "Filmmaking",
  "Firefighters",
  "Fishing",
  "Fitness",
  "Flash",
  "Food",
  "Football",
  "Foreign",
  "Found Family",
  "Fugitive",
  "Full CGI",
  "Full Color",
  "Gambling",
  "Gangs",
  "Gender Bending",
  "Ghost",
  "Go",
  "Goblin",
  "Gods",
  "Golf",
  "Gore",
  "Guns",
  "Gyaru",
  "Handball",
  "Henshin",
  "Heterosexual",
  "Hikikomori",
  "Hip-hop Music",
  "Historical",
  "Homeless",
  "Horticulture",
  "Ice Skating",
  "Idol",
  "Indigenous Cultures",
  "Inn",
  "Isekai",
  "Iyashikei",
  "Jazz Music",
  "Josei",
  "Judo",
  "Kaiju",
  "Karuta",
  "Kemonomimi",
  "Kids",
  "Kingdom Management",
  "Konbini",
  "Kuudere",
  "Lacrosse",
  "Language Barrier",
  "Long Strip",
  "Lost Civilization",
  "Love Triangle",
  "Mafia",
  "Magic",
  "Mahjong",
  "Maids",
  "Makeup",
  "Male Harem",
  "Male Protagonist",
  "Marriage",
  "Martial Arts",
  "Matchmaking",
  "Matriarchy",
  "Medicine",
  "Medieval",
  "Memory Manipulation",
  "Mermaid",
  "Meta",
  "Metal Music",
  "Military",
  "Mixed Gender Harem",
  "Mixed Media",
  "Monster Boy",
  "Monster Girl",
  "Mopeds",
  "Motorcycles",
  "Mountaineering",
  "Musical Theater",
  "Mythology",
  "Natural Disaster",
  "Necromancy",
  "Nekomimi",
  "Ninja",
  "No Dialogue",
  "Noir",
  "Non-fiction",
  "Nudity",
  "Nun",
  "Office",
  "Office Lady",
  "Oiran",
  "Ojou-sama",
  "Orphan",
  "Otaku Culture",
  "Outdoor Activities",
  "Pandemic",
  "Parenthood",
  "Parkour",
  "Parody",
  "Philosophy",
  "Photography",
  "Pirates",
  "Poker",
  "Police",
  "Politics",
  "Polyamorous",
  "Post-Apocalyptic",
  "POV",
  "Pregnancy",
  "Primarily Adult Cast",
  "Primarily Animal Cast",
  "Primarily Child Cast",
  "Primarily Female Cast",
  "Primarily Male Cast",
  "Primarily Teen Cast",
  "Prison",
  "Proxy Battle",
  "Psychosexual",
  "Puppetry",
  "Rakugo",
  "Real Robot",
  "Rehabilitation",
  "Reincarnation",
  "Religion",
  "Rescue",
  "Restaurant",
  "Revenge",
  "Robots",
  "Rock Music",
  "Rotoscoping",
  "Royal Affairs",
  "Rugby",
  "Rural",
  "Samurai",
  "Satire",
  "School",
  "School Club",
  "Scuba Diving",
  "Seinen",
  "Shapeshifting",
  "Ships",
  "Shogi",
  "Shoujo",
  "Shounen",
  "Shrine Maiden",
  "Skateboarding",
  "Skeleton",
  "Slapstick",
  "Slavery",
  "Snowscape",
  "Software Development",
  "Space",
  "Space Opera",
  "Spearplay",
  "Steampunk",
  "Stop Motion",
  "Succubus",
  "Suicide",
  "Sumo",
  "Super Power",
  "Super Robot",
  "Superhero",
  "Surfing",
  "Surreal Comedy",
  "Survival",
  "Swimming",
  "Swordplay",
  "Table Tennis",
  "Tanks",
  "Tanned Skin",
  "Teacher",
  "Teens Love",
  "Tennis",
  "Terrorism",
  "Time Loop",
  "Time Manipulation",
  "Time Skip",
  "Tokusatsu",
  "Tomboy",
  "Torture",
  "Tragedy",
  "Trains",
  "Transgender",
  "Travel",
  "Triads",
  "Tsundere",
  "Twins",
  "Unrequited Love",
  "Urban",
  "Urban Fantasy",
  "Vampire",
  "Vertical Video",
  "Veterinarian",
  "Video Games",
  "Vikings",
  "Villainess",
  "Virtual World",
  "Vocal Synth",
  "Volleyball",
  "VTuber",
  "War",
  "Werewolf",
  "Wilderness",
  "Witch",
  "Work",
  "Wrestling",
  "Writing",
  "Wuxia",
  "Yakuza",
  "Yandere",
  "Youkai",
  "Yuri",
  "Zombie"
]