import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { ReactQueryProvider } from "@/lib/react-query";
import ApolloProvider from "@/lib/apollo-provider";
import { Toaster } from "sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import Script from "next/script";
import Sidebar from "@/components/sidebar/sidebar";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        {process.env.ENV == 'DEVELOPMENT' && (
          <head>
            <Script
              crossOrigin="anonymous"
              src="//unpkg.com/react-scan/dist/auto.global.js"
            />
          </head>
        )}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ApolloProvider>
          <ReactQueryProvider>
            <NuqsAdapter>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                  <div className="flex flex-col min-h-screen">
                    <Header />
                    <div className="flex-1 pt-[calc(1rem+var(--header-height))]"> 
                      <Sidebar className="shrink-0" />
                      <main className="container mx-auto md:pl-[var(--sidebar-width)]">
                        {children}
                      </main>
                    </div>
                  </div>
                <Toaster theme="dark" />
              </ThemeProvider>
            </NuqsAdapter>
          </ReactQueryProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}